# Generated by Django 3.1.4 on 2021-05-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Group Name')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.group', verbose_name='Group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Group',
                'verbose_name_plural': 'Room Groups',
            },
        ),
    ]
