# Generated by Django 3.1.4 on 2021-05-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_group_roomgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupDefinition',
        ),
    ]
