# Generated by Django 3.1.4 on 2021-05-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210507_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupDefinition',
            new_name='CustomGroup',
        ),
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'My Group', 'verbose_name_plural': 'My Groups'},
        ),
    ]
