# Generated by Django 3.1.4 on 2021-05-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210507_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='roomgroup',
            name='room',
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.DeleteModel(
            name='RoomGroup',
        ),
    ]
