# Generated by Django 3.1.4 on 2021-05-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210513_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='DevicePlaceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicePlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.deviceplace', verbose_name='Place')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'DevicePlaceTag',
                'verbose_name_plural': 'DevicePlacesTag',
            },
        ),
    ]
