# Generated by Django 3.1.4 on 2021-05-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_deviceplacetag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('Rojo', 'red'), ('Verde', 'green'), ('Azul', 'blue')], default='', max_length=100, verbose_name='Color'),
        ),
    ]
