# Generated by Django 3.1.4 on 2021-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210514_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('red', 'Rojo'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarillo'), ('purple', 'Morado'), ('cyan', 'Celeste'), ('brown', 'Marrón'), ('grey', 'Gris')], max_length=100, verbose_name='Color'),
        ),
    ]
