# Generated by Django 3.1.4 on 2021-09-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210514_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Alias'),
        ),
    ]
