# Generated by Django 3.1.4 on 2021-12-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_invoice_invoicefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warranty_from',
            field=models.DateField(verbose_name='Warranty from'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warranty_to',
            field=models.DateField(verbose_name='Warranty to'),
        ),
    ]
