# Generated by Django 3.1.4 on 2021-12-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20211202_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='device',
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Reference'),
        ),
        migrations.CreateModel(
            name='InvoiceDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Device')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice device',
                'verbose_name_plural': 'Invoice devices',
            },
        ),
    ]
