# Generated by Django 3.1.4 on 2021-12-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20211202_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceplace',
            name='tags',
            field=models.ManyToManyField(to='inventory.Tag'),
        ),
        migrations.DeleteModel(
            name='DevicePlaceTag',
        ),
    ]
