# Generated by Django 3.1.4 on 2021-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20211214_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceplace',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Tag'),
        ),
    ]
