# Generated by Django 3.1.4 on 2021-12-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20211214_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Device'),
        ),
    ]
