# Generated by Django 4.0.5 on 2022-06-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20220620_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modificationrequestfile',
            name='modificationRequest',
        ),
        migrations.DeleteModel(
            name='ModificationRequest',
        ),
        migrations.DeleteModel(
            name='ModificationRequestFile',
        ),
    ]
