# Generated by Django 3.1.4 on 2021-05-14 05:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0002_eventlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=100, null=True, verbose_name='Details'),
        ),
    ]
