# Generated by Django 3.1.4 on 2022-05-25 10:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0003_auto_20210514_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', ckeditor.fields.RichTextField(blank=True, default='', max_length=10000, verbose_name='Json')),
            ],
            options={
                'verbose_name': 'ReportScheduledTask',
                'verbose_name_plural': 'ReportScheduledTask',
            },
        ),
    ]
