# Generated by Django 3.1.4 on 2022-05-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0004_reportscheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportscheduledtask',
            name='manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gorilla.manifest', verbose_name='Manifest'),
        ),
    ]
