# Generated by Django 3.1.4 on 2022-05-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0007_auto_20220525_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, default='', verbose_name='Json')),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_report', to='gorilla.manifest', verbose_name='Manifest')),
            ],
            options={
                'verbose_name': 'Gorilla Report',
                'verbose_name_plural': 'Gorilla Reports',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Report Type',
                'verbose_name_plural': 'Report Types',
            },
        ),
        migrations.DeleteModel(
            name='ReportScheduledTask',
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_report', to='gorilla.reporttype', verbose_name='Type'),
        ),
    ]
