# Generated by Django 3.1.4 on 2022-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0010_report_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Json'),
        ),
    ]
