# Generated by Django 3.1.4 on 2022-06-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorilla', '0011_auto_20220620_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='type',
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
    ]
